name: Build, Test, Dialyze

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - 'master'

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['23', '24', '25']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_version}}
          rebar3-version: '3.17.0'
      - name: Run tests
        run: rebar3 ct
      - name: Generate documentation
        run: rebar3 edoc
      - shell: bash
        name: Dialyzer
        run: rebar3 dialyzer
      - shell: bash
        name: Escriptize
        run: rebar3 as prod escriptize
      - shell: bash
        name: Smoke test
        run: ./erlperf 'timer:sleep(1).'
