name: Build, Test, Dialyze

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - 'master'

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [23, 24, 25]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: rebar3 ct
      - name: Generate documentation
        run: rebar3 edoc
      - shell: bash
        name: Dialyzer
        run: rebar3 dialyzer
      - shell: bash
        name: Escriptize
        run: rebar3 as prod escriptize
      - shell: bash
        name: Smoke test
        run: ./erlperf 'timer:sleep(1).'